const latSlo: { [key: string ]: string} = {
    'Ducks, Geese, and Waterfowl': 'Race, gosi in ostale vodne ptice',
    'Cormorants and Shags': 'Kormorani in vranjeki',
    'Grebes': 'Ponirki',
    'Shearwaters and Petrels': 'Viharniki',
    'Boobies and Gannets': 'Strmoglavci',
    'Pelicans': 'Pelikani',
    'Skuas and Jaegers': 'Govnačke',
    'Gulls, Terns, and Skimmers': 'Galebi, čigre in škarjekljuni',
    'Sandpipers and Allies': 'Kljunači in drugi',
    'Flamingos': 'Plamenci',
    'Storks': 'Štorklje',
    'Cranes': 'Žerjavi',
    'Herons, Egrets, and Bitterns': 'Čaplje in drugi',
    'Rails, Gallinules, and Coots': 'Tukalice',
    'Pheasants, Grouse, and Allies': 'Kure',
    'Pigeons and Doves': 'Golobi in grlice',
    'Hawks, Eagles, and Kites': 'Orli',
    'Falcons and Caracaras': 'Sokoli',
    'Owls': 'Sove',
    'Nightjars and Allies': 'Podhujke',
    'Swifts': 'Hudourniki',
    'Swallows': 'Lastovke',
    'Cuckoos': 'Kukavice',
    'Cockatoos': 'Kakaduji',
    'Rollers': 'Zlatovranke',
    'Bee-eaters': 'Legati',
    'Kingfishers': 'Vodomci',
    'Hoopoes': 'Smrdokavre',
    'Woodpeckers': 'Žolne',
    'Crows, Jays, and Magpies': 'Vrane',
    'Old World Flycatchers': 'Muharji',
    'Shrikes': 'Srakoperji',
    'Thrushes and Allies': 'Drozgi',
    'Accentors': 'Pevke',
    'Dippers': 'Povodni kosi',
    'Waxwings': 'Pegami',
    'Bearded Reedling': 'Brkate sinice',
    'Penduline-Tits': 'Plašice',
    'Long-tailed Tits': 'Dolgorepke',
    'Tits, Chickadees, and Titmice': 'Sinice',
    'Nuthatches': 'Brglezi',
    'Treecreepers': 'Drevesni plezalčki',
    'Wallcreeper': 'Skalni plezalček',
    'Wrens': 'Stržki',
    'Grassbirds and Allies': 'Cvrčalci',
    'Cisticolas and Allies': 'Brškinke',
    'Bush Warblers and Allies': 'Svilnice',
    'Reed Warblers and Allies': 'Vrtniki in trstnice',
    'Sylviid Warblers and Allies': 'Penice',
    'Leaf Warblers': 'Listnice',
    'Kinglets': 'Kraljički',
    'Wagtails and Pipits': 'Pastirice in cipe',
    'Larks': 'Škrjanci',
    'Longspurs and Snow Buntings': 'Snežni strnadi',
    'Old World Buntings': 'Strnadi',
    'Old World Sparrows': 'Vrabci',
    'Finches, Euphonias, and Allies': 'Ščinkavci',
    'Old World Orioles': 'Kobilarji',
    'Starlings': 'Škorci'
}

export default latSlo;